version: '3.8'

services:
  db:
    image: postgres:17
    container_name: auth_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "${DB_PORT}:${DB_PORT}" # todo УДАЛИТЬ на проде
    secrets:
      - db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth_net
    command: postgres -c max_connections=${DB_MAX_CONNECTIONS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:8.6.3-alpine
    container_name: auth_cache
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}" # todo УДАЛИТЬ на проде
    secrets:
      - redis_password
    networks:
      - auth_net
    entrypoint: ["/bin/sh", "-c", "exec redis-server --requirepass \"$(cat /run/secrets/redis_password)\" --tcp-backlog 2048"]
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "$$(cat /run/secrets/redis_password)", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  server:
    build: .
    # local test images
#    image: app-server:${SERVER_IMAGE_TAG}
    container_name: auth_server
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    env_file:
      - .env
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
      DB_PASSWORD_FILE: /run/secrets/db_password
      SECRET_KEY_FILE: /run/secrets/secret_key
      JWT_PUBLIC_KEY_FILE: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_FILE: /run/secrets/jwt_private_key
    secrets:
      - redis_password
      - db_password
      - secret_key
      - jwt_public_key
      - jwt_private_key
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - auth_net

networks:
  auth_net:
    driver: bridge

volumes:
  postgres_data:

secrets:
  redis_password:
    file: .secrets/redis_password
  db_password:
    file: .secrets/db_password
  secret_key:
    file: .secrets/secret_key
  jwt_public_key:
    file: .secrets/jwt_public_key.pem
  jwt_private_key:
    file: .secrets/jwt_private_key.pem
