# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "0.0.0.0"
    ubuntu.vm.network "forwarded_port", guest: 5432, host: 5432 # todo УДАЛИТЬ на проде!
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.name = "vagrant-vm-ubuntu-nir-spring-2026"
    end
    ubuntu.vm.synced_folder "../app", "/app"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = "4"
    vb.memory = "8192"
#     vb.cpus = "2"
#     vb.memory = "4096"
    vb.check_guest_additions=false
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get upgrade -y
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    sudo groupadd docker
    sudo usermod -aG docker vagrant

    # Сетевые настройки ядра для нагрузочных тестов
    sudo tee /etc/sysctl.d/99-nir.conf > /dev/null <<EOF
net.core.somaxconn = 4096
net.ipv4.tcp_max_syn_backlog = 8192
EOF
    sudo sysctl --system
  SHELL
end
